### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'task'

### ISSUE THREAD

**Issue by dilipv09** [Coldog2333/pytoflow#10]
Facing below error while attempting to use 'run.py'. 
command-
python run.py --f1 example/im1.png --f2 example/im3.png --o example/out.png --gpuID 0

Error-
Loading TOFlow Net... Traceback (most recent call last):
  File "run.py", line 112, in <module>
    net = TOFlow(intPreprocessedHeight, intPreprocessedWidth, cuda_flag=CUDA)
TypeError: __init__() missing 1 required positional argument: 'task'

Any help. Thanks!!

**Comment by Coldog2333** [comment]
You can try to add an arg `task='interp'` to solve this problem.
**Noted that the codes in ./unstable were not tested, so you may debug by yourself if you want to use the codes.**

**Comment by dilipv09** [comment]
I tried that too but still facing the same problem.

Best regards,
Dilip Verma

**Comment by Coldog2333** [comment]
I tried. Though there were other bugs, this problem was solved.
Please debug it by yourself now, since I am busy with other stuff these days.
