### ISSUE TITLE
SR results not clear

### ISSUE THREAD

**Issue by dister520** [Coldog2333/pytoflow#11]
Hi,
Trying to reproduce the SR results but it the output of the image appears to be the same size as the input. Is there a way to validate SR?

**Comment by linkboyx** [comment]
It seems that missing SR (upsampling) module in Network. Could you please check it ?@Coldog2333

**Comment by Coldog2333** [comment]
Thank you for your interest.

Yes, the sizes of the input and output are the same.
When preprocessing, I downsampled the original image and resized it to the original size as the blurred input. 
Then let it generate a more clear image as the output. So I think we don't have to implement the upsampling module in the network.

For example: [256, 512] --downsampling--> [128, 256] --upsampling (resize)--> [256, 512] --predict--> [256, 512](more clear, similar to the origin image)
