### ISSUE TITLE
Why SR results is one output image?

### ISSUE THREAD

**Issue by wwlCape** [Coldog2333/pytoflow#12]
Hi, thank you for your great reimplementation work. As we know, toflow can achieve video SR tasks. I want to know how to generate consecutive HR video frames instead of one frame from 7 consecutive LR video frames.

**Comment by ahmadmughees** [comment]
@wwlCape take 7 frames as a sequence and put that in loop.

**Comment by wwlCape** [comment]
Thank you for your advice. But in the Vimeo90K dataset, each clip has only 7 frames, so this method can generate 7 continuous HR frames. Is there anything I misunderstand?

**Comment by ahmadmughees** [comment]
Welcome. :) well as far as dataset is concerned, yes it contains 7 frames and it will output one frame as its just for benchmarking. But you can download the original Vimeo videos and test on them as well as a part of Video Super resolution. 

Best. 
Mughees

**Comment by wwlCape** [comment]
OK, I can test this method on other datasets. Thank you again. :)
