### ISSUE TITLE
2x model

### ISSUE THREAD

**Issue by ycjing** [Coldog2333/pytoflow#13]
Hi @Coldog2333 

Thank you for the great code! I noticed that the code is for 4x super-resolution. Is it possible to train a 2x super-resolution model? Thanks.

Best,
Yongcheng

**Comment by Coldog2333** [comment]
Hello.

I remembered it was trained to complete 2x super-resolution.
But anyway, of course the algorithm can be applied to any-x super-resolution.
For example, you can upsample to 2^{n}-x picture with TOFlow and then downsample it to m-x picture (m < 2^{n}).  

You can get more information and have a deeper understanding after reading the paper.

Best,
Coldog

**Comment by Coldog2333** [comment]
I am sorry, it does perform 4x super-resolution since it transforms [n, m] to [2n, 2m].

In this way, I want to confirm what do you mean the "2x super-resolution"?

**Comment by ycjing** [comment]
Hi @Coldog2333 

Thank you for the response! I think you have got my point. By saying 2x super-resolution, I mean the output image is 2x in size than the input image, i.e. transforming a n x m image to 2n x 2m. 

Now, the code is actually performing 4x resolution, where the output is 4x in size than the input (as also indicated in the paper), i.e., n x m to 4n x 4m. I wonder whether it is possible to revise the code for 2x super-resolution. Thank you!

Best,
Yongcheng

**Comment by Coldog2333** [comment]
Hello,

Yes, sure. The size is not the problem.
Checking **Issue #11** may be helpful for you. 

Best,
Coldog
