### ISSUE TITLE
About the evaluation results

### ISSUE THREAD

**Issue by cewang-sysu** [Coldog2333/pytoflow#4]
Since the results on video denoising of pytoflow is very different from original results of toflow, so could you put how you evaluate your models? on matlab or using skimage of python?@Coldog2333

**Comment by Coldog2333** [comment]
I evaluated the performance as the authors did, using the same software (matlab) and the same .m code as you can see in ./evaluation. Perhaps it is a lucky model on denoising task :)

**Comment by cewang-sysu** [comment]
Very thanks for your reply! The difference is very amazing. You work here with pytorch is very useful! Thanks again! @Coldog2333

**Comment by Coldog2333** [comment]
@mars11121 Thank you. :)
But just in case, if you still want to check my proposed performance, you can use the scripts in this repository and evaluate with the model in ./toflow_models/denoise.pkl. If you have any other question about that, just feel free to open an issue.
