### ISSUE TITLE
problems when using pytoflow

### ISSUE THREAD

**Issue by cewang-sysu** [Coldog2333/pytoflow#6]
when I use the code on Viemo90K, I have encountered a problem that the value range of processed 
images of the model is out of (0, 1), have you encountered this similar problem? and could you 
give me some help? thanks a lot!

**Comment by Coldog2333** [comment]
Hello. I think you can print these images out to see whether they have something wrong. Sometimes the values maybe not so important, they can be rescaled when you output them as images.

**Comment by cewang-sysu** [comment]
okay, thanks a lot @Coldog2333; and I find that on line214, train.py, the check_point should be corrected to check_loss, which is used to replace original check_loss = 1.

**Comment by Coldog2333** [comment]
Oh, thank you for your reminder! 
(It has been corrected.)

**Comment by Coldog2333** [comment]
I remember that I checked all of the codes on my machine before pushing them. Maybe I should check it once again. (If I have time...)

**Comment by cewang-sysu** [comment]
fine, and your contribution is really useful for my work~

**Comment by Coldog2333** [comment]
Glad to hear that. Thank you for your appreciation. :)
If you have any other questions, just feel free to new an issue.

**Comment by Coldog2333** [comment]
Hello, I check the codes of this repository today and figure out the reason for the problem you encountered.
This is a bug or something like updated feature of matplotlib.
If you use a matplotlib with version like 2.0.2, the problem will not occur.

reference: https://github.com/matterport/Mask_RCNN/issues/69
